services:
  database:
    image: postgres
    container_name: stokse-db
    restart: always
    env_file:
      - db_variables.env
    volumes:
      - stokse_db:/var/lib/postgresql/data

  django:
    build:
      context: ./stokse-server
    volumes:
      - ./stokse-server:/django
      - /var/www/django_static:/django/static
      - /var/www/django_media:/django/media
    ports:
      - "8000:8000"
    image: django:stokse_server_api
    container_name: stokse_server_container
    depends_on:
      - database

  react:
    build:
      context: ./stokse-client
    volumes:
      - /var/www/stokse_client:/react/dist/web

    image: react:stokse_client_build
    container_name: stokse_client_build

volumes:
  stokse_db:
