services:
  database:
    image: postgres
    container_name: stokse-db
    restart: always
    environment:
      POSTGRES_DB: stokse
      POSTGRES_USER: stokse_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - stokse_db:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 8000:8000
      - 443:443
    volumes:
      - django_static:/var/www/django_static
      - django_media:/var/www/django_media
      - spa_build:/var/www/react
      - ./nginx/nginx-api-setup.conf:/etc/nginx/conf.d/api.conf
      - ./nginx/nginx-web-setup.conf:/etc/nginx/conf.d/web.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django
      - react

  django:
    build:
      context: ./stokse-server
    volumes:
      - ./stokse-server:/django
      - django_static:/django/static
      - django_media:/django/media
    image: django:stokse_server_api
    container_name: stokse_server_container
    depends_on:
      - database

  react:
    build:
      context: ./stokse-client
    volumes:
      - spa_build:/react/dist/web
    image: react:stokse_client_build
    container_name: stokse_client_build

volumes:
  spa_build:
  django_media:
  django_static:
  stokse_db:
