server {
    listen 80;
    server_name app.stokse.com;

    # return 301 https://$host$request_uri;

    location / {
        root /var/www/react;
        try_files $uri /index.html;
    }

    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;
    gzip_vary on;  # exp
    gzip_min_length 256;
    gzip_proxied any;  # Enable gzip for all proxied requests
    gzip_disable "msie6";  # Disable gzip for Internet Explorer 6

    keepalive_timeout 75;  # Slightly increased for potentially better resource use

    location ~ /\. {
        deny all;  # Deny access to hidden files (like .htaccess)
    }

    client_max_body_size 50M;
}
